language: python
cache:
  - pip
  - apt
python:
  - "3.4"
before_install:
  - sudo apt-get -qq update
# for PySide/QT4
  - sudo apt-get install -y build-essential git cmake libqt4-dev libphonon-dev python3.4-dev libxml2-dev libxslt1-dev qtmobility-dev libqtwebkit-dev
install:
  - "pip install -r test_requirements.txt"
script:
  - "py.test"
